---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cmhautomacion/repositories/SeeFerreteria/
    - /bin/cp -R backend $DEPLOYPATH/
    - /bin/cp -R frontend/dist $DEPLOYPATH/frontend/dist/
    - cd $DEPLOYPATH/backend && npm install --omit=dev
    - /bin/touch $DEPLOYPATH/backend/tmp/restart.txt
